---
shardCount: 1
prefix:
  - "#!"
status: online
game:
  type: Playing
  name:
    - "with Ganymede"
    - "with wrenches"
  url: https://twitch.tv/k3rn31p4nic
  interval: 60
music:
  status: true
  passes: 1
logLevel: 6
